apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartloom-app
spec:
  replicas: 2  # Inicialmente duas réplicas
  selector:
    matchLabels:
      app: cartloom-app
  template:
    metadata:
      labels:
        app: cartloom-app
    spec:
      containers:
      - name: cartloom
        image: your-dockerhub-repo/cartloom:latest  # Imagem Docker da sua aplicação
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: DYNAMODB_HOST
          value: "dynamodb-service"
        - name: KAFKA_HOST
          value: "kafka-service"
---
apiVersion: v1
kind: Service
metadata:
  name: cartloom-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cartloom-app
