apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb
        image: amazon/dynamodb-local
        ports:
        - containerPort: 8000
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: dynamodb
