apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cartloom-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cartloom-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  # Escala se o uso de CPU ultrapassar 50%
